#!/usr/bin/perl

if (@ARGV < 1){
    print " Calling sequence is:\n";
    die "skydip_az.pl -az azimuth_value_in_degrees\n";
}


$homedir = $ENV{"HOME"};
$file = "$homedir/skydip_new.pako";
 
for ($i=0; $i <= $#ARGV; $i++) {
    if ($ARGV[$i] eq "-az") {
	$azimuth = $ARGV[$i+1];}
}


open OUT, ">$file";
print OUT "!\n";
print OUT "!  Id: diyv2.pako, A Catalano version skydip up and down 2014-01-19 \n";
print OUT "!      Make smaller AM steps when arriving at low elevation\n";
print OUT "!  AM= 1.1, 1.4, 1.7, 2. then 2.15, 2.30, 2.45, 2.60, 2.75, 2.90\n";
print OUT "!      from diy-test-12 by Hans Ungerechts\n";
print OUT "!\n";
print OUT "!say \"  --> diyup.pako 10 steps in AM 1.1 to 2.9 (20deg)\" \n";
print OUT "!\n";
print OUT "set level 5 5\n";
print OUT "!\n";
print OUT "say \"==============================================================\"\n";
print OUT "say \"You must specify the current azimuth in the diyup.pako script \"\n";
print OUT "say \"before executing it otherwise you risk to waste a long time \"\n";
print OUT "say \"for the telescope to move to the requested Azimuth.\"\n";
print OUT "say \"==============================================================\"\n";
print OUT " !\n";
print OUT " source DIY-start HO $azimuth 30      !!!!!!!!!!!!!!!!!!!!!!!!!!!! slowly tuning of the kids\n";
print OUT " track 0 0 /tsub 20 /syst true\n";
print OUT " start\n";
print OUT " source DIY-start HO $azimuth 25      !!!!!!!!!!!!!!!!!!!!!!!!!!!!\n";
print OUT " track 0 0 /tsub 20 /syst true\n";
print OUT " start\n";
print OUT " source DIY-start HO $azimuth 20      !!!!!!!!!!!!!!!!!!!!!!!!!!!!\n";
print OUT " track 0 0 /tsub 20 /syst true\n";
print OUT " start\n";
print OUT " pause \"Tune the KIDs and type c to continue (q to quit)\"\n";
print OUT " !\n";
print OUT " !!!!! ======= skydip up starting   ========\n";
print OUT " !\n";
print OUT " source DIY-Tip HO $azimuth 45         !!!!!!!!!!!!!!!!!!!  \"Source\" at azimuth 180\n";
print OUT " !                                        !!  elevation 10 [deg] ! Please do not modify the elevation\n";
print OUT " ! \n";
print OUT " DIY /clear                               !!  clear DIY\n";
print OUT " !\n";
print OUT " define real el yEl \n";
print OUT " !\n";
print OUT " for air 2.9 to 2.15 by -0.15               !!  2nd loop over airmass\n";
print OUT "   !\n";
print OUT "   el  = 180.0/Pi*asin(1/air)\n";
print OUT "   yEl = el-45\n";
print OUT "   SAY \"Elevation: \" 'el'\n";
print OUT "   !\n";
print OUT "   pako\\SUBSCAN -                         !!  tune\n";
print OUT "   0.0000000E+00   yEl*3600.00 -         !!  el. offset in [arc sec]\n";
print OUT "  /croFlag O -\n";
print OUT "  /system trueHorizon -\n";
print OUT "  /tSubscan    6.00000 -                !!  6 [sec] (6 sec needed for tuning\n";
print OUT "  /tune -\n";
print OUT "  /type track\n";
print OUT "  !\n";
print OUT "  pako\\SUBSCAN -                         !!  on sky\n";
print OUT "   0.0000000E+00   yEl*3600.00 -         !!  el. offset in [arc sec]\n";
print OUT "  /croFlag O -\n";
print OUT "  /system trueHorizon -\n";
print OUT "  /tSubscan    11.00000 -                !!  11 [sec]\n";
print OUT "  /type track\n";
print OUT "  !\n";
print OUT "next air\n";
print OUT "!\n";
print OUT "!PAUSE\n";
print OUT "!\n";
print OUT "for air 2 to 1.1 by -0.3               !!  1st loop over airmass\n";
print OUT "  !\n";
print OUT "  el  = 180.0/Pi*asin(1/air)\n";
print OUT "  yEl = el-45\n";
print OUT "  SAY \"Elevation: \" 'el'\n";
print OUT "  !\n";
print OUT "  pako\\SUBSCAN -                         !!  tune\n";
print OUT "   0.0000000E+00   yEl*3600.00 -         !!  el. offset in [arc sec]\n";
print OUT "  /croFlag O -\n";
print OUT "  /system trueHorizon -\n";
print OUT "  /tSubscan    6.00000 -                !!  6 [sec]\n";
print OUT "  /tune -\n";
print OUT "  /type track\n";
print OUT "  !\n";
print OUT "  pako\\SUBSCAN -                         !!  on sky\n";
print OUT "   0.0000000E+00   yEl*3600.00 -         !!  el. offset in [arc sec]\n";
print OUT "  /croFlag O -\n";
print OUT "  /system trueHorizon -\n";
print OUT "  /tSubscan    11.00000 -                !!  11 [sec]\n";
print OUT "  /type track\n";
print OUT "  !\n";
print OUT "next air\n";
print OUT "!   \n";
print OUT "start\n";
print OUT "!\n";
print OUT "clear plot                               !! setup for preview plot\n";
print OUT "limits -45*3600 45*3600 -45*3600 80*3600 !! pako plots offsets in [arc sec]\n";
print OUT "greg\\set box match\n";
print OUT "\n";
print OUT "   DIY\n";
print OUT "!! DIY /purpose \"tuned Tip\"                 !! set purpose for DIY\n";
print OUT "\n";
print OUT "limits -1 1 0 90                         !! box, Y = El. [deg]\n";
print OUT "axis yl\n";
print OUT "axis xu /tick no\n";
print OUT "axis yr\n";
print OUT "axis xl /tick no\n";
print OUT "label \"Elevation [deg]\" /y\n";
print OUT "draw text   0  100 \"=== Upward Skydip ===\" /user\n";
print OUT "!\n";
print OUT "set level 0 0\n";
print OUT "!\n";
print OUT "!\n";
print OUT "PAUSE \"Continue/Quit? [c/q]\" \n";
print OUT "!!!!! ======= skydip down starting   ========\n";
print OUT "\n";
print OUT "source DIY-start HO $azimuth 65.38      !!!!!!!!!!!!!!!!!!!!!!!!!!!!\n";
print OUT "track 0 0 /tsub 20 /syst true\n";
print OUT "start\n";
print OUT "pause \"Tune the KIDs and type c to continue (q to quit)\"\n";
print OUT "!\n";
print OUT "!\n";
print OUT "source DIY-Tip HO $azimuth 45                !!  \"Source\" at azimuth 180\n";
print OUT "!                                        !!  elevation 10 [deg]\n";
print OUT "DIY /clear                               !!  clear DIY\n";
print OUT "!\n";
print OUT "!define real el yEl \n";
print OUT "\n";
print OUT "   for air 1.1 to 2 by +0.3               !!  1st loop over airmass\n";
print OUT "\n";
print OUT "  el  = 180.0/Pi*asin(1/air)\n";
print OUT "  yEl = el-45\n";
print OUT "  SAY \"Elevation: \" 'el'\n";
print OUT "  !\n";
print OUT "  pako\\SUBSCAN -                         !!  tune\n";
print OUT "   0.0000000E+00   yEl*3600.00 -         !!  el. offset in [arc sec]\n";
print OUT "  /croFlag O -\n";
print OUT "  /system trueHorizon -\n";
print OUT "  /tSubscan    6.00000 -                !!  6 [sec]\n";
print OUT "  /tune -\n";
print OUT "  /type track\n";
print OUT "  !\n";
print OUT "\n";
print OUT "  pako\\SUBSCAN -                         !!  on sky\n";
print OUT "   0.0000000E+00   yEl*3600.00 -         !!  el. offset in [arc sec]\n";
print OUT "  /croFlag O -\n";
print OUT "  /system trueHorizon -\n";
print OUT "  /tSubscan    11.00000 -                !!  11 [sec]\n";
print OUT "  /type track\n";
print OUT "  !\n";
print OUT "next air\n";
print OUT "\n";
print OUT "\n";
print OUT "   for air 2.15 to 2.9 by +0.15               !!  2nd loop over  airmass   !! down\n";
print OUT "!\n";
print OUT "  el  = 180.0/Pi*asin(1/air)\n";
print OUT "  yEl = el-45\n";
print OUT "  SAY \"Elevation: \" 'el'\n";
print OUT "  !\n";
print OUT "  pako\\SUBSCAN -                         !!  tune\n";
print OUT "   0.0000000E+00   yEl*3600.00 -         !!  el. offset in [arc sec]\n";
print OUT "  /croFlag O -\n";
print OUT "  /system trueHorizon -\n";
print OUT "  /tSubscan    6.00000 -                !!  6 [sec]\n";
print OUT "  /tune -\n";
print OUT "  /type track\n";
print OUT "  !\n";
print OUT "  pako\\SUBSCAN -                         !!  on sky\n";
print OUT "   0.0000000E+00   yEl*3600.00 -         !!  el. offset in [arc sec]\n";
print OUT "  /croFlag O -\n";
print OUT "  /system trueHorizon -\n";
print OUT "  /tSubscan    11.00000 -                !!  11 [sec]\n";
print OUT "  /type track\n";
print OUT "  !\n";
print OUT "next air\n";
print OUT "!\n";
print OUT "!    \n";
print OUT "start\n";
print OUT "\n";
print OUT "clear plot                               !! setup for preview plot\n";
print OUT "limits -45*3600 45*3600 -45*3600 80*3600 !! pako plots offsets in [arc sec]\n";
print OUT "greg\\set box match\n";
print OUT "\n";
print OUT "   DIY\n";
print OUT "!! DIY /purpose \"tuned Tip\"                 !! set purpose for DIY\n";
print OUT "\n";
print OUT "limits -1 1 0 90                         !! box, Y = El. [deg]\n";
print OUT "axis yl\n";
print OUT "axis xu /tick no\n";
print OUT "axis yr\n";
print OUT "axis xl /tick no\n";
print OUT "label \"Elevation [deg]\" /y\n";
print OUT "draw text   0  100 \"=== downward Skydip ===\" /user\n";
print OUT "!\n";
print OUT "set level 0 0\n";


close OUT;


